### ISSUE TITLE
VENDOR_HOME set incorrectly on RHEL 6.6

### ISSUE THREAD

**Issue by jw-dell** [ENGYS/HELYX-OS#1]
I'm attempting to use HELYX-OS 2.3.1 on a RHEL 6.6 system. I have the path to OpenFOAM 2.4.0 set in the preferences to: /cm/shared/apps/OpenFOAM/gcc/OpenFOAM-2.4.0

When attempting to create a mesh, HELYX-OS is setting VENDOR_HOME to /cm/shared/apps/OpenFOAM/gcc, which causes meshing to fail as the executables are unable to be found. ENV_LOADER appears to be set correctly.

I also manually added a '/' character to the end of the path in the application.properties file and that did not resolve the issue.

**Comment by donminoti** [comment]
Hi jw-dell,
Have you found a solution or guideline to set up (install) Helyx Os 2.3.1 on CentOs 6.x ? i have opened a thread on: 
http://www.cfd-online.com/Forums/openfoam-meshing-snappyhexmesh/117183-installing-helyxos-32-64bit-linux-distributions.html#post591986
Thanks

**Comment by HELYX-OS** [comment]
Hi,
sorry for the late reply.
I need to know a couple of informations:
1) how have you installed openfoam240? By following the "openfoam.org" instructions or have you compiled the source code by yourself?
2) Does the path "/cm/shared/apps/OpenFOAM/gcc/OpenFOAM-2.4.0" contains the "etc" folder?
3) What is the value of the ENV_LOADER variable?

**Comment by HELYX-OS** [comment]
We close this issue because no answer has been given.
If needed feel free to re-open the issue.

Cheers
