### ISSUE TITLE
Feature request: Apply button on "Solver Settings" and "Numerical Schemes" tabs

### ISSUE THREAD

**Issue by attesz86** [ENGYS/HELYX-OS#13]
When changing solution and schemes parameters "on-the-fly" it would be great to apply those changes and write them into the corresponding foam dictionary without saving the case again during simulation.

**Comment by HELYX-OS** [comment]
Hi,
this feature is already present inside our backlog and will be implemented in a future version of HELYX-OS.
Cheers
