### ISSUE TITLE
BlockMesh Command not found

### ISSUE THREAD

**Issue by sunish5** [ENGYS/HELYX-OS#19]
Hi, I Installed Helyx-OS and the compatible Opem FOAM version on a Virtual Machine in the Home folder. But when I press create mesh in Helyx-OS it says blockMesh command not found.I can notice that the blockMesh.dict is not found there. What should I do?

**Comment by HELYX-OS** [comment]
Have you linked HELYX-OS with OpenFOAM by using the "Edit>Preferences" dialog?
If so, what is the value for the "Core Folder" entry?

**Comment by sunish5** [comment]
Thank you for your quick reply 

I/home/sunish/OpenFOAM-4.1

**Comment by HELYX-OS** [comment]
Ok it is correct.
- In the same preferences dialog, is the "Use Docker" checkbox NOT selected?
- Does the openfoam installation works fine?
- Can you paste here (or attach a text file) the whole error message?

**Comment by sunish5** [comment]
/home/sunish/Ahmed/mesh_parallel.run: line 32: blockMesh: command not found
/home/sunish/Ahmed/mesh_parallel.run: line 26: /home/sunish/OpenFOAM/etc/bashrc: No such file or directory

**Comment by sunish5** [comment]
Use docker checkbox not selected. OpenFoam installation was fine

**Comment by HELYX-OS** [comment]
The error message says:
"/home/sunish/OpenFOAM/etc/bashrc"
but it should say:
"/home/sunish/OpenFOAM-4.1/etc/bashrc"

Can you please check the file "/home/sunish/.HELYX-OS/application.properties" and paste here the line that contains the "openfoam.basedir" key?

**Comment by sunish5** [comment]
Just a correction I changed the core directory path. Following is the updated error 

/home/sunish/Ahmed/mesh_parallel.run: line 32: blockMesh: command not found
/home/sunish/OpenFOAM-4.1/etc/config.sh/mpi: line 46: mpicc: command not found

Permission denied when I type '/home/sunish/.HELYX-OS/application.properties' in the terminal

**Comment by sunish5** [comment]
tried chmod 755 with /home/sunish/.HELYX-OS/application.properties but no output

**Comment by HELYX-OS** [comment]
No it is a text file, you should just display the contents by running "more  /home/sunish/.HELYX-OS/application.properties"

**Comment by sunish5** [comment]
Ok thanks. There it is                /home/sunish/OpenFOAM-4.1

**Comment by sunish5** [comment]
I chose the option 2)HELYX-OS-GUI and Kernel but there was error in fetching OpenFoam or something, so I installed OpenFoam manually using the link in your website

**Comment by HELYX-OS** [comment]
Ok, give us some time and we will come back to you with some ideas.
Thanks

**Comment by sunish5** [comment]
Ok it seems like the problem with blockMesh is solved by setting the environment variable as instructed in the OpenFoam website. 

But I am getting this error  /home/sunish/OpenFOAM-4.1/etc/config.sh/mpi: line 46: mpicc: command not found

**Comment by HELYX-OS** [comment]
What is your OS?
Is it a 32 or 64 bit system?

Do you confirm that sourcing the core and running the "blockMesh" utility from within a case folder works fine and no exceptions are thrown?
Because your error make us think that it is a compilation or a missing dependencies issue

**Comment by sunish5** [comment]
Hello, 
I installed OpenFOAM 4 and linked to it. That seems to have solved the problem. Thank you very much for your help

**Comment by HELYX-OS** [comment]
Glade you manage to solve your issue.
