### ISSUE TITLE
wrong pressure unit indication

### ISSUE THREAD

**Issue by saladinheart** [ENGYS/HELYX-OS#2]
On Helyx OS v2.3.1 while setting up a VOF model, boundary conditions and Fields initialisation for the pressure should be given in Pa and not in m2/s2 as indicated in the gui.

**Comment by saladinheart** [comment]
Is is not a bug, so I close the issue, ambiguity comes form the fact that P_rgh is in Pa while P is in m2/s2.

**Comment by HELYX-OS** [comment]
Ok!
