### ISSUE TITLE
Bug , semes to be link to Java JRE

### ISSUE THREAD

**Issue by fredvol** [ENGYS/HELYX-OS#20]
Hello,
I install yesterday Helyx-OS , using the script:
HELYX-OS-2.4.0-linux-x86_64.bin
It was working ok.

Today "create mesh " do not work anymore.

I got the message attached in the Terminal runing Helys-Os.
I'am runing on linux-mint18 , 64bit machine.
I just instal a VNC server in between , which I do not think it is link.
Could anyone help?

Thanks in advance
Have a nice day.
fred

[bug_Java_HelyxOS.txt](https://github.com/ENGYS/HELYX-OS/files/1820857/bug_Java_HelyxOS.txt)

**Comment by HELYX-OS** [comment]
Hi,
are you using the Parallel Works interface?
Can you double check by pressing the "Run Cloud" button on the toolbar and see what is selected on the "Execution Driver" drop down menu?
It should be set to "Localhost" in order to run on your machine.

**Comment by fredvol** [comment]
Hi ,
Yes it was on parallel works.
Thanks, you save my weekend! I started to restore all my system!
Thanks again for your prompt response!
Have a nice day!
Fred

Le 17 mars 2018 8:56 AM, HELYX-OS Development Team <notifications@github.com> a écrit :

Hi,
are you using the Parallel Works interface?
Can you double check by pressing the "Run Cloud" button on the toolbar and see what is selected on the "Execution Driver" drop down menu?
It should be set to "Localhost" in order to run on your machine.

**Comment by HELYX-OS** [comment]
I'm glad that I could help.
Have a nice day!
