### ISSUE TITLE
I cannot execute HELIX-OS.sh

### ISSUE THREAD

**Issue by anderteicher** [ENGYS/HELYX-OS#21]
![helixos](https://user-images.githubusercontent.com/10604538/38724892-d281898a-3f05-11e8-8784-3293f44e54bd.PNG)

I'm trying to run HELIX  on ubuntu in the sub environment of win 10 anniversary
But when I execute the .sh file with the command:

 ./HELIX-OS.sh

All stops without any error with the screenshot attached.

Any opinion?

Thank you in advance

**Comment by HELYX-OS** [comment]
Hi,
the error message is saying that you cannot run a graphical application in that environment.
You need to install an X server as stated here:
https://askubuntu.com/questions/823352/windows-10-bash-cannot-connect-to-display/823358#823358

**Comment by anderteicher** [comment]
Thank you very much,

SOLVED! :)
