### ISSUE TITLE
I can't change any parameter

### ISSUE THREAD

**Issue by anderteicher** [ENGYS/HELYX-OS#22]
Good morning,

I'm running helix in ubuntu Subsystem for Windows 10.

The cursor does not allow editing of fields, like for example the geometry's dimensions and so I can't change the dimensions from the default values.

Any solutions?

thank you in advance

**Comment by HELYX-OS** [comment]
Hi,
this scenario is nor supported nor tested.
We provide a native windows version for paying customers.
If you are interested please contact us at info@engys.com.
Cheers
