### ISSUE TITLE
BUILD FAILED ./build_src.xml:28: ./lib does not exist

### ISSUE THREAD

**Issue by thima2017** [ENGYS/HELYX-OS#24]
I'm trying to compile on Lubuntu 18.04 using the README.md step by step tutorial.
I have installed ant 1.10.3-1ubuntu0.1 and default-jdk, which depends on openjdk-11-jdk (10.0.2+13-1ubuntu0.18.04.4).
Here is my console output:

user@user:/media/user/11828f6f-0a0f-43b6-9985-1a87a0dbf845/user/bouilds/helyx-os/inst-dir$ ant -buildfile build_src.xml
Buildfile: /media/user/11828f6f-0a0f-43b6-9985-1a87a0dbf845/user/bouilds/helyx-os/inst-dir/build_src.xml

init:
    [mkdir] Created dir: /media/user/11828f6f-0a0f-43b6-9985-1a87a0dbf845/user/bouilds/helyx-os/inst-dir/build

compile:
    [javac] Compiling 1134 source files to /media/user/11828f6f-0a0f-43b6-9985-1a87a0dbf845/user/bouilds/helyx-os/inst-dir/build

BUILD FAILED
/media/user/11828f6f-0a0f-43b6-9985-1a87a0dbf845/user/bouilds/helyx-os/inst-dir/build_src.xml:28: /media/user/11828f6f-0a0f-43b6-9985-1a87a0dbf845/user/bouilds/helyx-os/inst-dir/lib does not exist.

Total time: 0 seconds
user@user:/media/user/11828f6f-0a0f-43b6-9985-1a87a0dbf845/user/bouilds/helyx-os/inst-dir$

**Comment by davideciani** [comment]
Hi thima2017,

can you make sure that:

1) point 3 of the tutorial refers to the INSTALLED helyxos (i.e. the folder where you have installed HELYX-OS using the HELYX-OS-2.4.0-linux-x86_64.bin installer

2) point 4 refers to the SOURCES cloned at point 2. 

3) after performing point 4 your "/home/user/Engys/HELYX-OS/vX.X.X"  folder should contain the following files:

COPYING
HELYX-OS.sh
README.md
bin
build
build_src.xml
dictData
ext
img
lib
src

With this folder structure it works.
If you have a different structure come back to us and we will see what's wrong.

**Comment by HELYX-OS** [comment]
Hi thima2017,

can you make sure that:

point 3 of the tutorial refers to the INSTALLED helyxos (i.e. the folder where you have installed HELYX-OS using the HELYX-OS-2.4.0-linux-x86_64.bin installer)

point 4 refers to the SOURCES cloned at point 2.

after performing point 4 your "/home/user/Engys/HELYX-OS/vX.X.X" folder should contain the following files:

COPYING
HELYX-OS.sh
README.md
bin
build
build_src.xml
dictData
ext
img
lib
src

With this folder structure it works.
If you have a different structure come back to us and we will see what's wrong.

**Comment by thima2017** [comment]
My mistake. I didn't read it carefully enough
