### ISSUE TITLE
Question: Helyx-OS development

### ISSUE THREAD

**Issue by dhombios** [ENGYS/HELYX-OS#25]
There hasn't been any code updates since 2016 in this project and the commercial version is in version 3.1.1 and it has received a major UI upgrade, while Helyx os is still in 2.4. Is this software still supported? Does it work with current OpenFoam releases?

**Comment by HELYX-OS** [comment]
Dear dhombios,

HELYX-OS is provided free of charge with limited support for specific OpenFOAM versions. The code is intended for academic use, so we may continue developing the tool depending on general feedback.
The current version of HELYX-OS is designed to work natively with OpenFOAM v4.1 and OpenFOAM v1606+, but you might be able to get it to work with more recent versions of OpenFOAM.
Please note, HELYX and HELYX-OS are two very different software tools. They’re unrelated, so comparing versions is irrelevant in this context.

**Comment by Mx74** [comment]
Hello,

Since it' snot possible anymore to install OF4 on a recent Ubuntu, I had to use Helyx-os with a more recent of OF.
It does work quite well, until I tried to transcient simulation with LES. 

It appears that Helyx doesn't write the fvSolution correctly with the new OF syntax for the residualControl: 

Old syntax: 
 residualControl
        {
            U
            {
                relTol 0;
                tolerance 1.0E-4;
            }

            k
            {
                relTol 0;
                tolerance 0.0001;
            }

            epsilon
            {
                relTol 0;
                tolerance 0.0001;
            }

            omega
            {
                relTol 0;
                tolerance 0.0001;
            }

            nuTilda
            {
                relTol 0;
                tolerance 0.0001;
            }

            T
            {
                relTol 0;
                tolerance 0.0001;
            }

            p_rgh
            {
                relTol 0;
                tolerance 0.0001;
            }

            p
            {
                relTol 0;
                tolerance 1.0E-4;
            }

            "alpha.*"
            {
                relTol 0;
                tolerance 0.0001;
            }

        }


New syntax asks for a single value:

residualControl
        {
            U 1.0E-4;
            k 0.0001;
            epsilon 0.0001;
            omega 0.0001;
            nuTilda 0.0001;
            T 0.0001;
            p_rgh 0.0001;
            p 1.0E-4;
            "alpha.*" 0.0001;
        }

Would it be possible to correct that point?
