### ISSUE TITLE
Error: Solution convergence criteria specified in PIMPLE.residualControl must be given as single values.

### ISSUE THREAD

**Issue by neznayer** [ENGYS/HELYX-OS#27]
Hello, could someone help me please:

I installed OpenFoam 7, and then the Helyx-OS v.2.4.0 (GUI only), but it seemed like there was different dictionaries format or something: when I try to run the case OF gives error:

```
-> FOAM FATAL ERROR:
[2] Solution convergence criteria specified in PIMPLE.residualControl must be given as single values. Corrector loop convergence criteria, if appropriate, are specified as dictionaries in PIMPLE.ResidualControl.
```

I read that Helyx-OS is designed for OpenFoam 4.x, so I installed OF 4.x as well in home folder using [these instructions](https://openfoamwiki.net/index.php/Installation/Linux/OpenFOAM-4.x/Ubuntu#Ubuntu_18.04)
It compiled without errors (icoFoam -help gives OpenFOAM-4.x )
But when I set the OF 4.x path (/home/anton/OpenFOAM/OpenFOAM-4.x) in [Edit]->[Preferences] in Helyx-OS, it gives

```
mpirun was unable to find the specified executable file, and therefore
did not launch the job. This error was first reported for process
rank 0; it may have occurred for other processes as well.
```

I also tried to install HELYX-OS again, in the folder where it was already installed, but with option
"GUI and Kernel"
The installation finishes almost instantly without any errors, but also without installing the kernel.

So my question is:
Is Helyx-OS working with OpenFoam 7? If so, then what am I doing wrong with setting up the case?
If not, what should I do to run the case?

My system is ubuntu 18.04 running on WSL

**Comment by neznayer** [comment]
I just managed to do make it work by adding an execution of a python script in the run script, which edits fvSolution and edits residualControl  part so it comply with Open Foam 7 format.

**Comment by HELYX-OS** [comment]
I’m happy to hear that you managed to get it to work with OF7.  Can you elaborate a bit further on the problems you had with OF4? It should work out of the box with OF4.

**Comment by kitupi** [comment]
I have the same problem ... can anybody tell me what to do for fix it ?

**Comment by Lianxiali** [comment]
Refer to https://www.cfd-online.com/Forums/openfoam-solving/205508-pimple-solver-error-residualcontrol-must-given-single-values.html.

Use (works for OF7)
residualControl
{
    U   1e-05;
    p   1e-04;
}
instead of (which works for OpenFOAM v1906)
    residualControl
    {
        U
        {
            tolerance   1e-05;
            relTol      0;
        }
        p
        {
            tolerance   1e-04;
            relTol      0;
        }
    }

**Comment by praneethTele** [comment]
@neznayer @HELYX-OS  Can you help me how it is resolved? If possible where the python script is added and what is in it? I tried making changes in this file panels/PimpleSettingsPanel.java . Output is in the format mentioned above. But , Case Setup option is  getting disabled because it is not able to read "Dictionary".
