### ISSUE TITLE
No lib folder

### ISSUE THREAD

**Issue by github-not-allow-me-to-delete-profile** [ENGYS/HELYX-OS#28]
When I tried to compile it I receiver error that folder `lib` is missing.

Is it possible to add pom.xml (maven) for example for storing all dependencies?

**Comment by HELYX-OS** [comment]
Hi Saatsazov,
are you sure you have followed the instructions thoroughly?
They have been tested and are known to work.

**Comment by github-not-allow-me-to-delete-profile** [comment]
Yes,
1. I've check versions 
```
>java --version
openjdk 13.0.1 2019-10-15
OpenJDK Runtime Environment (build 13.0.1+9)
OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
```
```
>ant -version
Apache Ant(TM) version 1.10.7 compiled on September 1 2019
```
```
>javac --version
javac 13.0.1
```
2. I've cloned this repo
`>git clone....`

3. run ant build 
```
>ant -buildfile build_src.xml
Buildfile: /Users/bagratsaatsazov/proj/HELYX-OS/build_src.xml

init:

compile:
    [javac] Compiling 1134 source files to /Users/bagratsaatsazov/proj/HELYX-OS/build
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 7
    [javac] warning: [options] source value 7 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 7 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] /Users/bagratsaatsazov/proj/HELYX-OS/src/eu/engys/application/AbstractApplication.java:47: error: package org.slf4j does not exist
    [javac] import org.slf4j.Logger;
```
this is just a beginning of errors


According to ant build script it tries to use 'lib' folder

```
	<property name="lib.dir" value="lib" />

	<path id="build.path">
		<fileset dir="${lib.dir}">
			<include name="**/*.jar" />
		</fileset>
	</path>
```
There is no such folder `lib` so I've created it. But it won't help

The original error with 
```
>ant -buildfile build_src.xml
Buildfile: /Users/bagratsaatsazov/proj/HELYX-OS/build_src.xml

init:

compile:
    [javac] Compiling 1134 source files to /Users/bagratsaatsazov/proj/HELYX-OS/build

BUILD FAILED
/Users/bagratsaatsazov/proj/HELYX-OS/build_src.xml:28: /Users/bagratsaatsazov/proj/HELYX-OS/lib does not exist.

Total time: 0 seconds
```

**Comment by HELYX-OS** [comment]
Saatsazov,

From the **Prerequisites** section:
1) Installation of **precompiled** HELYX-OS X.X.X.
Have you done that? Have you installed HELYX-OS via the provided installer before trying to compile the sources?
2) **openjdk** is not **oracle java**

Then, as stated in the **Steps to Compile** section: you have to "git clone" the sources in a **separate** folder and then move them inside the **precompiled** HELYX-OS folder structure (point 3 and 4)

Finally you can compile the sources.
Please read **carefully** the instructions and HELYX-OS will compile fine.

**Comment by github-not-allow-me-to-delete-profile** [comment]
I'm simple curious why do I need sominth precompiled if i tried to compile software from source code? Is it some part of software with closed source code?

**Comment by HELYX-OS** [comment]
HELYX-OS requires some external libraries to work.
These libraries are not included in the source package (and that's the main reason you got the errors listed in your first post).
Plus, HELYX-OS come with its own java runtime.
All of this components need to be located in specific directories, and this structure is provided by the precompiled installation.
With the provided instructions you just re-compile the main HELYX-OS code inside its pre-installed working environment.

**Comment by github-not-allow-me-to-delete-profile** [comment]
Thank you
