### ISSUE TITLE
Install Helys-OS from script

### ISSUE THREAD

**Issue by piiq** [ENGYS/HELYX-OS#29]
Hi, I am trying to automate installation of Helyx-OS to use it on a mac over X11 from a container. When I manually install via the linux binaries it into the container it works fine, but I can’t seem to automate the installation to pack it into the dockerfile. 
I have tried EOF’ing parameters, echo’ing parameters and lots of other stuff (yes, stdin, expect etc.), but nothing seems to work. 

Is there any way installation of Helys-OS can be automated by a bash script?

**Comment by davideciani** [comment]
Hi piiq, unfortunately Helyx-OS has no support for unattended installation.

**Comment by HELYX-OS** [comment]
Hi piiq, unfortunately Helyx-OS has no support for unattended installation.

**Comment by piiq** [comment]
This is very unfortunate. One more question, if you don't mind. When trying to build Helys-OS from source it requires the files that are placed by the installer execution prior to that.
Is it just the files that are needed, or is the installer creating some links on the system level?

**Comment by HELYX-OS** [comment]
The installer does not create any system level links, just follow the provided instructions and everything should compile fine.
