### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by d-gaf** [ENGYS/HELYX-OS#3]
Tired to install per these instructions:
http://engys.github.io/HELYX-OS/installation/

Using Ubuntu 14.04 LTS in a Virtual Box

I could not copy and paste the error. There should be a screen snapshot attached!
![helyx-os](https://cloud.githubusercontent.com/assets/19839898/15934164/87359512-2e30-11e6-8f8b-cfb61dea7d96.JPG)

**Comment by HELYX-OS** [comment]
Hi,

have you installed HELYX-OS as sudo or as normal user?

Anyway that "Exec format error" makes me think that the installation didn't completed successfully. Do you mind, delete the current installation and reinstall HELYX-OS?
There are even chances that the installer has been corrupted while downloading.
Can you try download the installer again?

If none of this works come back here and we will investigate more.

**Comment by d-gaf** [comment]
Thank you for the fast response. I will try all of your suggestion and let you know!
I "installed" as a User. I was never prompted for sudo.

**Comment by HELYX-OS** [comment]
User is the correct one, so you did it right.
I wait for your updates.

**Comment by d-gaf** [comment]
OK. I tried deleting the installation and re-installed with the original download. It failed the same way.
I re-downloaded the file and re-installed and still failed.
I did have to use the sudo when it wanted to load/update the OpenFOAM files. It looks like they were loaded into /opt . I have several variables. Could Virtual Box be an issue? I use it for so many other distributions and have not had this kind of problem.

**Comment by HELYX-OS** [comment]
Ok another couple of questions:

1) is your ubuntu a 64 bit machine (can you post the output of the command "uname -m)"?
2) are you using bash or sh?

**Comment by d-gaf** [comment]
I was pretty sure it was 64 bit but I checked and it is 32 bit. I'm not sure why i picked that I can go get the 64 bit version and try it.
I believe it is bash. If I try sh --version I get an error but typing bash --version I get 4.3.11
for reference uname -r = 3.16.0-71-generic

**Comment by HELYX-OS** [comment]
bash is fine!
On a 64 bit machine everything should work fine, please let me know anyway.

**Comment by d-gaf** [comment]
The downloaded file said x86_64 so I thought it might work on both. The website says it's 64 bit so it was a little confusing. I'm installing the 64 bit OS now.

**Comment by HELYX-OS** [comment]
x86_64 is for 64 bit processors. 
i386 is for 32 bit processors.

for now only the x86_64 version is available

**Comment by d-gaf** [comment]
I'm soooo sorry to have wasted your time with that.

During the install I did receive so warnings but it said the installation was complete.
![helyx-os2](https://cloud.githubusercontent.com/assets/19839898/15941003/6f3cb5d2-2e4c-11e6-8575-9ad5bcfc4033.JPG)
I went ahead and tried to run it and it is starting but then I got this message:
![helyx-os3](https://cloud.githubusercontent.com/assets/19839898/15941051/95cb6d4c-2e4c-11e6-87fe-ad1373c8199f.JPG)
Is there just some setup I have to follow?

**Comment by HELYX-OS** [comment]
The warnings are related to the OpenFOAM installation, please refer to the http://openfoam.org/ website for that.
The HELYX-OS message instead means that you need to link HELYX-OS with the openfoam installation.
Click OK on the message, then go on the top left corner and hit Edit>Preferences.
Here you can set the path to the OpenFOAM installation.
If you have installed OpenFOAM via our installer it should be in "/opt/openfoam30".
Set that path and you are done!

**Comment by d-gaf** [comment]
The Openfoam files are not there. The warnings must have been real. :-) 
OK thanks so much for your help!

**Comment by d-gaf** [comment]
Oh sorry can I load Open foam 3.0.1? Or do I have to stick with the 2.4.x?

**Comment by HELYX-OS** [comment]
We will release soon a new version of HELYX-OS that will support OpenFOAM 3.0.1, for now you should rely on openfoam 240.
Sorry to said it wrong on the previous message, it is "/opt/openfoam240".

**Comment by d-gaf** [comment]
Thanks again!

**Comment by HELYX-OS** [comment]
No worries, here to help!
