### ISSUE TITLE
HELYX-OS-2.4.0 installation problem on Ubuntu 18.04.4 LTS

### ISSUE THREAD

**Issue by f1aerofanatic** [ENGYS/HELYX-OS#30]
Hi everyone,

This is my first post here, so I am happy with any help I can get. I am also quite the newbie with Ubuntu and the codes in the terminal, so I am sorry beforehand if I ask stupid questions :)

I have the following problem:
- Freshly installed Ubuntu on a usb stick with persistent storage, according to theisarticle (https://www.howtogeek.com/howto/14912/create-a-persistent-bootable-ubuntu-usb-flash-drive/)
- Downloaded the latest helyx-os release
- Followed the installation instructions on the installation page.
- Install the GUI and Kernel

Then I get the following problem:

_Please select your linux distribution:
1) Ubuntu (14.04 or later)
2) Other
#? 1
Installing HELYX-OS kernel
Ign:1 cdrom://Ubuntu 18.04.4 LTS _Bionic Beaver_ - Release amd64 (20200203.1) bionic InRelease
Hit:2 cdrom://Ubuntu 18.04.4 LTS _Bionic Beaver_ - Release amd64 (20200203.1) bionic Release
Hit:3 http://security.ubuntu.com/ubuntu bionic-security InRelease                                                                   
Hit:4 http://archive.ubuntu.com/ubuntu bionic InRelease                                                                             
Hit:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease                                   
Ign:6 https://www.openfoam.org/download/ubuntu bionic InRelease                                   
Err:8 https://www.openfoam.org/download/ubuntu bionic Release
  Redirection from https to 'http://dl.openfoam.org/ubuntu/dists/bionic/Release' is forbidden [IP: 52.56.138.82 443]
Reading package lists... Done                      
W: Target Sources (main/source/Sources) is configured multiple times in /etc/apt/sources.list:2 and /etc/apt/sources.list:4
W: Target Sources (restricted/source/Sources) is configured multiple times in /etc/apt/sources.list:2 and /etc/apt/sources.list:4
E: The repository 'http://www.openfoam.org/download/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: Target Sources (main/source/Sources) is configured multiple times in /etc/apt/sources.list:2 and /etc/apt/sources.list:4
W: Target Sources (restricted/source/Sources) is configured multiple times in /etc/apt/sources.list:2 and /etc/apt/sources.list:4

Installation completed!_

When starting Helyx-os from the installation folder with the command: ./HELYX-OS.sh

As suggested by the terminal text, when I want to set the core and paraview locations in the preferences, I cannot do this because they are not installed.

Do you have any suggestions to help?

Thanks alot!

Ramon

**Comment by HELYX-OS** [comment]
Hi f1aerofanatic,
unfortunately the automated installation of OpenFOAM version 4.1 is not available anymore.
You need to follow the instructions [here](https://openfoam.org/download/4-1-source) and compile the source code.

**Comment by f1aerofanatic** [comment]
Thank you for the quick reply Helyx-OS team!

Any problems during the OpenFOAM 4.1 installation should be reported to the OpenFOAM team I presume?

My final stupid question  for today: what would be the problem when I install the latest OpenFOAM version instead of 4.1?

**Comment by HELYX-OS** [comment]
Q: Any problems during the OpenFOAM 4.1 installation should be reported to the OpenFOAM team I presume?
A: correct

Q: My final stupid question for today: what would be the problem when I install the latest OpenFOAM version instead of 4.1?
A: Some dictionaries may be written with a different syntax that is not supported by a newer version of OpenFOAM. For small changes you can still use the custom interface available in HELYX-OS which allows you to override the way things are written to disk

**Comment by f1aerofanatic** [comment]
Thank you HELYX-OS team!
