### ISSUE TITLE
HELYX OS won't open after install - Error VTKSettings

### ISSUE THREAD

**Issue by bradymhammond** [ENGYS/HELYX-OS#31]
I just installed HELYX and am getting the following errors. The GUI won't even open. I an using Ubuntu 18.04 LTS with OpenFOAM v1912 on a windows 10 machine. Any help would be greatly appreciated!

-----------------------------------------------------------------------------------------
0 - main                           - ERROR VTKSettings                     - vtkInteractionStyleJava NOT loaded
     1 - main                           - ERROR VTKSettings                     - vtkInteractionWidgetsJava NOT loaded
...

14 - main                           - ERROR VTKSettings                     - vtkWebCoreJava NOT loaded
    14 - main                           - ERROR VTKSettings                     - vtkChartsCoreJava NOT loaded
---------------------------------------------------------------------------------------------

I tried following these steps from an OpenFOAMwiki to fix it and it didn't work.

tar -xjf HELYX-OS-2.4.0-linux-x86_64.tar.bz2
cd Engys/HELYX-OS
rm -rf jre
ln -s /usr/lib/jvm/java-8-openjdk-amd64/jre jre
cd v2.4.0
rm -rf ext/lib*
cp -a /usr/lib/*/libvtk* ext/
rm lib/vtk6.jar
mkdir lib/vtk6
cd lib/vtk6
unzip /usr/share/java/vtk6.jar
sed -i \
  -e 's=.*vtkParallelMPI4PyJava.*==' \
  -e 's=.*vtkRenderingVolumeOpenGLNewJava.*==' \
  -e 's=.*vtkRenderingExternalJava.*==' \
  -e 's=.*vtkRenderingFreeTypeOpenGL2Java.*==' \
  -e 's=.*vtkRenderingVolumeAMRJava.*==' \
  -e 's=.*vtkRenderingContextOpenGL2Java.*==' \
  -e 's=.*vtkRenderingVolumeOpenGL2Java.*==' \
  -e 's=.*vtkRenderingOpenGL2Java.*==' \
  -e 's=.*vtkDomainsChemistryOpenGL2Java.*==' \
  -e 's=.*vtkIOADIOSJava.*==' \
  -e 's=.*vtkFiltersPythonJava.*==' \
  -e 's=.*vtkFiltersStatisticsGnuRJava.*==' \
  -e 's=.*vtkAcceleratorsPistonJava.*==' \
  -e 's=.*vtkAcceleratorsDaxJava.*==' \
  -e 's=.*vtkInfovisParallelJava.*==' \
  vtk/vtkNativeLibrary.java
javac vtk/vtkNativeLibrary.java
zip -r ../vtk6.jar *
cd ../..

This still didn't work.

I found that it might be an existing library error so I installed some libraries with the following commands. This came from another github issue page.

sudo apt-get install vtk6
sudo apt-get install libvtk6-java
sudo apt-get install openjdk-8-jre
sudo apt-get install openjdk-8-jdk
sudo apt install libglu1-mesa

I can't get it to open with these errors. Any advice?

**Comment by davideciani** [comment]
Hi bradymhammond,
We’ve never tried running HELYX-OS/OpenFOAM using the Ubuntu shell in Windows 10. Instead, we offer a native Windows version to our paid support customers

**Comment by HELYX-OS** [comment]
Hi bradymhammond ,
We’ve never tried running HELYX-OS/OpenFOAM using the Ubuntu shell in Windows 10. Instead, we offer a native Windows version to our paid support customers
