### ISSUE TITLE
BUILD FAILED, helyx-os opens but only simple solver

### ISSUE THREAD

**Issue by tomasreabe** [ENGYS/HELYX-OS#33]
Hello,
I have downloaded and installed Helyx-os 2.4.0 binary, 
    I did this the first time as HELYX-OS-GUI
    I did this the second time as HELYX-OS-GUI and Kernel
    I did this the third time as HELYX-OS-GUI
Each time the install said it completed successfully; to delete the install I just deleted the HELYX-OS folders (is there some step I missed)

When i try to build from source I get the message the build failed:
`troy@troy-GS73VR-6RF:~/Engys/HELYX-OS/v2.4.0$  ant -buildfile build_src.xml
Buildfile: /home/troy/Engys/HELYX-OS/v2.4.0/build_src.xml

init:
    [mkdir] Created dir: /home/troy/Engys/HELYX-OS/v2.4.0/build

compile:
    [javac] Compiling 1134 source files to /home/troy/Engys/HELYX-OS/v2.4.0/build
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 7
    [javac] warning: [options] source value 7 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 7 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] /home/troy/Engys/HELYX-OS/v2.4.0/src/eu/engys/util/ui/stepcomponent/FlatButtonUI.java:46: warning: SwingUtilities2 is internal proprietary API and may be removed in a future release
    [javac] import sun.swing.SwingUtilities2;
    [javac]                 ^
    [javac] /home/troy/Engys/HELYX-OS/v2.4.0/src/eu/engys/util/ui/TreeUtil.java:129: error: incompatible types: Enumeration<TreeNode> cannot be converted to Enumeration<DefaultMutableTreeNode>
    [javac]         Enumeration<DefaultMutableTreeNode> e = parent.children();
    [javac]                                                                ^
    [javac] /home/troy/Engys/HELYX-OS/v2.4.0/src/eu/engys/util/ui/stepcomponent/FlatButtonUI.java:118: warning: SwingUtilities2 is internal proprietary API and may be removed in a future release
    [javac]     		FontMetrics fm = SwingUtilities2.getFontMetrics(b, g);
    [javac]     		                 ^
    [javac] /home/troy/Engys/HELYX-OS/v2.4.0/src/eu/engys/util/ui/stepcomponent/FlatButtonUI.java:125: warning: SwingUtilities2 is internal proprietary API and may be removed in a future release
    [javac]     			SwingUtilities2.drawStringUnderlineCharAt(b, g,text, mnemonicIndex, textRect.x + getTextShiftOffset(), textRect.y + fm.getAscent() + getTextShiftOffset());
    [javac]     			^
    [javac] /home/troy/Engys/HELYX-OS/v2.4.0/src/eu/engys/util/ui/stepcomponent/FlatButtonUI.java:130: warning: SwingUtilities2 is internal proprietary API and may be removed in a future release
    [javac]     			SwingUtilities2.drawStringUnderlineCharAt(b, g,text, mnemonicIndex, textRect.x, textRect.y + fm.getAscent());
    [javac]     			^
    [javac] /home/troy/Engys/HELYX-OS/v2.4.0/src/eu/engys/util/ui/stepcomponent/FlatButtonUI.java:132: warning: SwingUtilities2 is internal proprietary API and may be removed in a future release
    [javac]     			SwingUtilities2.drawStringUnderlineCharAt(b, g,text, mnemonicIndex, textRect.x - 1, textRect.y + fm.getAscent() - 1);
    [javac]     			^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 1 error
    [javac] 9 warnings

BUILD FAILED
/home/troy/Engys/HELYX-OS/v2.4.0/build_src.xml:28: Compile failed; see the compiler error output for details.

Total time: 7 seconds
`

I am able to launch HELYX-OS and set up and run a simulation, 
but the only Solution Algorithm I have in Solver Settings is the "Simple" the box is greyed out and I am unable to select any other solver. 

I have OPENfoam 5.X installed.

is this a problem coming from the failed build, or is HELYX looking for something in OPENfoam 5.x that is missing or somewhere else?

Thanks
Troy

**Comment by HELYX-OS** [comment]
Hi Troy,
which java version are you using to compile HELYX-OS?
Just type "java -version" on the command line

**Comment by tomasreabe** [comment]
Hello, Thanks for the quick response.
see below
`troy@troy-GS73VR-6RF:~$ java -version
java version "14.0.2" 2020-07-14
Java(TM) SE Runtime Environment (build 14.0.2+12-46)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)

troy@troy-GS73VR-6RF:~$ javac -version
javac 14.0.2
`

**Comment by HELYX-OS** [comment]
Troy,
do you mind try and use ORACLE jdk8?
This should make it work.

You can find it here:
https://www.oracle.com/it/java/technologies/javase/javase-jdk8-downloads.html

**Comment by tomasreabe** [comment]
I will give it a try, Thanks

**Comment by tomasreabe** [comment]
I did change Java
`troy@troy-GS73VR-6RF:~/Engys/HELYX-OS/v2.4.0$  java -version
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)
troy@troy-GS73VR-6RF:~/Engys/HELYX-OS/v2.4.0$  javac -version
javac 1.8.0_261
`
I deleted the engys folder,
re-installed Helyx-os 2.4.0 binary,
I did this as HELYX-OS-GUI and Kernel

i moved the downloaded git files and tried to build.
It took 8 seconds compaired to 7 seconds with java 14 but still ended in BUILD FAILED

`troy@troy-GS73VR-6RF:~/Engys/HELYX-OS/v2.4.0$  ant -buildfile build_src.xml
Buildfile: /home/troy/Engys/HELYX-OS/v2.4.0/build_src.xml

init:
    [mkdir] Created dir: /home/troy/Engys/HELYX-OS/v2.4.0/build

compile:
    [javac] Compiling 1134 source files to /home/troy/Engys/HELYX-OS/v2.4.0/build
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 7
    [javac] warning: [options] source value 7 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 7 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] /home/troy/Engys/HELYX-OS/v2.4.0/src/eu/engys/util/ui/stepcomponent/FlatButtonUI.java:46: warning: SwingUtilities2 is internal proprietary API and may be removed in a future release
    [javac] import sun.swing.SwingUtilities2;
    [javac]                 ^
    [javac] /home/troy/Engys/HELYX-OS/v2.4.0/src/eu/engys/util/ui/TreeUtil.java:129: error: incompatible types: Enumeration<TreeNode> cannot be converted to Enumeration<DefaultMutableTreeNode>
    [javac]         Enumeration<DefaultMutableTreeNode> e = parent.children();
    [javac]                                                                ^
    [javac] /home/troy/Engys/HELYX-OS/v2.4.0/src/eu/engys/util/ui/stepcomponent/FlatButtonUI.java:118: warning: SwingUtilities2 is internal proprietary API and may be removed in a future release
    [javac]     		FontMetrics fm = SwingUtilities2.getFontMetrics(b, g);
    [javac]     		                 ^
    [javac] /home/troy/Engys/HELYX-OS/v2.4.0/src/eu/engys/util/ui/stepcomponent/FlatButtonUI.java:125: warning: SwingUtilities2 is internal proprietary API and may be removed in a future release
    [javac]     			SwingUtilities2.drawStringUnderlineCharAt(b, g,text, mnemonicIndex, textRect.x + getTextShiftOffset(), textRect.y + fm.getAscent() + getTextShiftOffset());
    [javac]     			^
    [javac] /home/troy/Engys/HELYX-OS/v2.4.0/src/eu/engys/util/ui/stepcomponent/FlatButtonUI.java:130: warning: SwingUtilities2 is internal proprietary API and may be removed in a future release
    [javac]     			SwingUtilities2.drawStringUnderlineCharAt(b, g,text, mnemonicIndex, textRect.x, textRect.y + fm.getAscent());
    [javac]     			^
    [javac] /home/troy/Engys/HELYX-OS/v2.4.0/src/eu/engys/util/ui/stepcomponent/FlatButtonUI.java:132: warning: SwingUtilities2 is internal proprietary API and may be removed in a future release
    [javac]     			SwingUtilities2.drawStringUnderlineCharAt(b, g,text, mnemonicIndex, textRect.x - 1, textRect.y + fm.getAscent() - 1);
    [javac]     			^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 1 error
    [javac] 9 warnings

BUILD FAILED
/home/troy/Engys/HELYX-OS/v2.4.0/build_src.xml:28: Compile failed; see the compiler error output for details.

Total time: 8 seconds
troy@troy-GS73VR-6RF:~/Engys/HELYX-OS/v2.4.0$  ./HELYX-OS.sh
`

Is there something else I should try, Is there something I should be deleteing to clear the last install?

**Comment by HELYX-OS** [comment]
Troy,
probably ant is still using the other java.
What is your JAVA_HOME variable set to?

**Comment by tomasreabe** [comment]
after your advice I did see JAVA_HOME variable set to 14 still, So I have updated that.

During the install of Helyx-os 2.4.0 binary I got the following output, is the Err: 7 a problem?

`Hit:1 http://us.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease              
Hit:3 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease            
Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease               
Hit:5 http://dl.openfoam.org/ubuntu focal InRelease                            
Ign:6 https://www.openfoam.org/download/ubuntu focal InRelease
Err:7 https://www.openfoam.org/download/ubuntu focal Release
  Redirection from https to 'http://dl.openfoam.org/ubuntu/dists/focal/Release' is forbidden [IP: 52.56.138.82 443]
Reading package lists... Done                    
E: The repository 'http://www.openfoam.org/download/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Installation completed!
`

**Comment by HELYX-OS** [comment]
Unfortunately the automatic installation of the kernel is not working because the download links are not valid anymore.
You should install it manually following the instructions on the openfoam website.
We do not have control over that part, sorry about that.

**Comment by tomasreabe** [comment]
I have already installed openfoam 5.x Just wondering if that was a problem

Just got this, Does this mean Success?

`troy@troy-GS73VR-6RF:~/Engys/HELYX-OS/v2.4.0$  ant -buildfile build_src.xml
Buildfile: /home/troy/Engys/HELYX-OS/v2.4.0/build_src.xml

init:
    [mkdir] Created dir: /home/troy/Engys/HELYX-OS/v2.4.0/build

compile:
    [javac] Compiling 1134 source files to /home/troy/Engys/HELYX-OS/v2.4.0/build
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
    [javac] /home/troy/Engys/HELYX-OS/v2.4.0/src/eu/engys/util/ui/stepcomponent/FlatButtonUI.java:46: warning: SwingUtilities2 is internal proprietary API and may be removed in a future release
    [javac] import sun.swing.SwingUtilities2;
    [javac]                 ^
    [javac] /home/troy/Engys/HELYX-OS/v2.4.0/src/eu/engys/util/ui/stepcomponent/FlatButtonUI.java:118: warning: SwingUtilities2 is internal proprietary API and may be removed in a future release
    [javac]     		FontMetrics fm = SwingUtilities2.getFontMetrics(b, g);
    [javac]     		                 ^
    [javac] /home/troy/Engys/HELYX-OS/v2.4.0/src/eu/engys/util/ui/stepcomponent/FlatButtonUI.java:125: warning: SwingUtilities2 is internal proprietary API and may be removed in a future release
    [javac]     			SwingUtilities2.drawStringUnderlineCharAt(b, g,text, mnemonicIndex, textRect.x + getTextShiftOffset(), textRect.y + fm.getAscent() + getTextShiftOffset());
    [javac]     			^
    [javac] /home/troy/Engys/HELYX-OS/v2.4.0/src/eu/engys/util/ui/stepcomponent/FlatButtonUI.java:130: warning: SwingUtilities2 is internal proprietary API and may be removed in a future release
    [javac]     			SwingUtilities2.drawStringUnderlineCharAt(b, g,text, mnemonicIndex, textRect.x, textRect.y + fm.getAscent());
    [javac]     			^
    [javac] /home/troy/Engys/HELYX-OS/v2.4.0/src/eu/engys/util/ui/stepcomponent/FlatButtonUI.java:132: warning: SwingUtilities2 is internal proprietary API and may be removed in a future release
    [javac]     			SwingUtilities2.drawStringUnderlineCharAt(b, g,text, mnemonicIndex, textRect.x - 1, textRect.y + fm.getAscent() - 1);
    [javac]     			^
    [javac] Note: /home/troy/Engys/HELYX-OS/v2.4.0/src/eu/engys/core/project/geometry/factory/DefaultGeometryFactory.java uses or overrides a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 6 warnings
     [copy] Copying 198 files to /home/troy/Engys/HELYX-OS/v2.4.0/build
    [touch] Creating /home/troy/Engys/HELYX-OS/v2.4.0/build/eu/engys/resources/version.properties
[propertyfile] Updating property file: /home/troy/Engys/HELYX-OS/v2.4.0/build/eu/engys/resources/version.properties

dist:
      [jar] Building jar: /home/troy/Engys/HELYX-OS/v2.4.0/lib/HELYX-OS.jar

BUILD SUCCESSFUL
Total time: 9 seconds
`

**Comment by HELYX-OS** [comment]
Troy, looks like it compiled.
Can you start the GUI?

**Comment by tomasreabe** [comment]
I can start the GUI and looks to be working, Thank You for all the help and support.
