### ISSUE TITLE
/home/marzban/Engys/HELYX-OS/v2.4.0/../jre/bin/java: No such file or directory

### ISSUE THREAD

**Issue by rezamarzban** [ENGYS/HELYX-OS#34]
![Screenshot_2020-10-26-17-34-07-948_tech ula](https://user-images.githubusercontent.com/73051714/97182220-81d80400-17b1-11eb-8a2b-a0a1abad0d9e.jpg)

See everything about my problem in the image:
While executing ./HELYX-OS.sh i give an error, However the file "java" is exist in bin directory!

And i granted all permission to everyuser!

**Comment by HELYX-OS** [comment]
Hi marzban2030,
can you attache a **text** file with the output of the command "./HELYX-OS.sh -V"?

**Comment by rezamarzban** [comment]
Hi, I attached a text file with output of the command "./HELYX-OS.sh -V" here:

[output.txt](https://github.com/ENGYS/HELYX-OS/files/5443994/output.txt)

**Comment by HELYX-OS** [comment]
Which OS are you using and which architecture (32 or 64 bit)?

**Comment by rezamarzban** [comment]
![Screenshot_2020-10-27-12-51-01-942_tech ula](https://user-images.githubusercontent.com/73051714/97281784-28281600-1853-11eb-95d8-142691a80b36.jpg)

According to the attached image:
OS is Ubuntu 18.04.2 and it is 64 bit (aarch64).
More information is available at the image also.

**Comment by HELYX-OS** [comment]
HELYX-OS is distributed with java for x86_64 architectures while you are using an arm64 architecture. You can try and download an oracle jdk8 for arm architectures and than replace the jre folder that comes with HELYX-OS with the one you find inside the jdk8 you have downloaded. However this is not a supported environment and we cannot guarantee it will work.

**Comment by rezamarzban** [comment]
Thank you very much for your help, I will work on this with your helps and guides.

**Comment by rezamarzban** [comment]
I worked on it with your guide, It works 50%!
(i used vncserver and vnc viewer for accessing GUI x11 environment also, While executing HELYX-OS in X11 environment it loads 50% approximately and show an error similar to below explained error).

The java problem has been solved by replacing Oracle jdk8 "jre" folder as you said, But there is an error while executing "./HELYX-OS.sh":
![IMG_20201027_150214](https://user-images.githubusercontent.com/73051714/97296387-d76de880-1865-11eb-9e5e-86ce0198a2b8.jpg)

Part of error message according to the attached image:
java.lang.UnsatisfiedLinkError: /home/marzban/Engys/HELYX-OS/v2.4.0/ext/libvtkFiltersStatisticsJava.so: /home/marzban/Engys/HELYX-OS/v2.4.0/ext/libvtkFiltersStatisticsJava.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)

So, I think that i can solve it by (Running amd64 binary on arm64):
1- adding amd64 support to dpkg architecture
2- installing multiarch support
3- installing all amd64 dependent packages
4- replacing amd64 Oracle jdk8 "jre" folder ...

**Comment by HELYX-OS** [comment]
Now the problem has moved to the 3D libraries which have been compiled and bridged towards the x86_64 java so yes, if you can just have amd64 support that will probably solve your issue. Also remember to put back the amd64 jre.

**Comment by rezamarzban** [comment]
Yes, Of course i should put back amd64 jre ...

**Comment by rezamarzban** [comment]
I have two ways to solving the overall problem:

Way one: compiling and installing HELYX-OS from source codes on my Ubuntu 18.04 arm64.

Way two: Adding amd64 support to my Ubuntu 18.04 arm64.

Every way has its own problems!

Let's go ...

**Comment by HELYX-OS** [comment]
For way one, the problem is not compiling HELYX-OS only, it is mostly on compiling the vtk libraries (the 3D ones).
I would go with way 2 If I were you.
Good luck!
