### ISSUE TITLE
Possible errors in compiling and installing HELYX-OS on arm64 Ubuntu 18.04

### ISSUE THREAD

**Issue by rezamarzban** [ENGYS/HELYX-OS#35]
Hello!

Currently i am git cloning the project ... (See image):
![Screenshot_2020-10-27-16-44-11-785_tech ula](https://user-images.githubusercontent.com/73051714/97306656-0428fc80-1874-11eb-896a-84f9d16a3835.jpg)

After git cloning the project a directory with name "HELYX-OS" has been created, I navigated to it and i found some files and one folder with name "src";
I executed "ant -buildfile build_src.xml" and i give an error (see image):
![Screenshot_2020-10-27-16-54-12-016_tech ula](https://user-images.githubusercontent.com/73051714/97308430-1a37bc80-1876-11eb-825a-730b0ee7073d.jpg)

Error:
BUILD FAILED
/home/marzban/HELYX-OS/build_src.xml:28: /home/marzban/HELYX-OS/lib does not exist.

**Comment by rezamarzban** [comment]
Lol! It is very complex issue!

After little thinking about previous error i installed HELYX-OS from its bin file to the my home directory, And i copied all source files and folders from git cloned directory to "Engys/HELYX-OS/v2.4.0". Then i executed "ant -buildfile build_src.xml" and i give an error (see image):
![Screenshot_2020-10-27-17-29-41-410_tech ula](https://user-images.githubusercontent.com/73051714/97311835-0b530900-187a-11eb-8344-b68019db82bf.jpg)

Because the error was long i executed above command again with output to a text file, And i attached the output.txt file below.
(However the output is bitly different from its first executing!)
![Screenshot_2020-10-27-17-47-20-369_tech ula](https://user-images.githubusercontent.com/73051714/97314024-84536000-187c-11eb-8c40-9b078f7da8b9.jpg)

Anyway see error at this output.txt file:

[output.txt](https://github.com/ENGYS/HELYX-OS/files/5445859/output.txt)

**Comment by HELYX-OS** [comment]
Ant is not using oracle jdk 8. Isn't it?
HELYX-OS is not meant to be compiled with a JDK other than the oracle one, as stated in the installation instructions.
If you want to make it compile with another JDK you need to change the source code were needed.

**Comment by rezamarzban** [comment]
![Screenshot_2020-10-27-17-55-20-980_tech ula](https://user-images.githubusercontent.com/73051714/97315125-a3062680-187d-11eb-862c-d3b06d9190a9.jpg)
According to the image it is jdk 11.
Which jdk should be used?!

**Comment by HELYX-OS** [comment]
Check the "Compiling HELYX-OS on your own">"Prerequisites" section here: https://github.com/ENGYS/HELYX-OS
It says Oracle JDK, which you can find here:
https://www.oracle.com/it/java/technologies/javase/javase-jdk8-downloads.html

**Comment by rezamarzban** [comment]
Thank you very much again,
You (company) support is excellent.

I will try this anyway ...

**Comment by rezamarzban** [comment]
![Screenshot_2020-10-27-19-33-23-201_tech ula](https://user-images.githubusercontent.com/73051714/97331717-eddc6a00-188e-11eb-9003-39167837f72e.jpg)
I built it successfully and replaced jre folder.

But when i execute "./HELYX-OS.sh" i give a long error. It say "cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)" for every ".so" files in the project.
How can i compile project to building ".so" files for arm64?!

**Comment by HELYX-OS** [comment]
marzban2030 the ".so" files are the vtk 3D libraries, written in c++, compiled for AMD64 machines and bridged against oracle java jdk8. You should recompile those for aarch64 architecture but it is a long path on which I cannot give you support.

**Comment by rezamarzban** [comment]
![Screenshot_2020-11-01-22-31-00-697_tech ula](https://user-images.githubusercontent.com/73051714/97811828-48603680-1c92-11eb-960d-f94a37be1449.jpg)
According to the image, i turned my Android phone with arm64 cpu into a PC with Intel/AMD cpu ... .

My android phone cpu: octa core cpu
Virtual machine cpu: 6 core2duo cpus

Ways:
1- adding amd64 architecture by dpkg? No
2- compiling by amd64 installed packages? No
3- Qemu-X86_64 user mode? No
4- X86_64 rootfs guest os isolating by proot + Qemu? No
5- Qemu-system-X86-64? Yes! It is very slow, But with correct configuration it will be at high performance as like as Host OS (Android).

For beginning (Use official linux kernel & ...) type in command line:
qemu-system-x86_64 -cpu core2duo -smp $(nproc) -m 384M -kernel linux -initrd initrd.gz -nographic -append "console=ttyS0 ramdisk_size=512000" -net nic -net user -no-reboot

It needs to be worked more on it for highest performance ...

Hints:
RAMDISK
Synce
...
