### ISSUE TITLE
Meshing problem

### ISSUE THREAD

**Issue by safif88** [ENGYS/HELYX-OS#37]
Hy,

OpenFoam 4.1 and HELYX-OS 2.4 are installed on Ubuntu 20.04 LTS. PitzDaily example of OpenFoam was tested from Terminal and its working, I got results in ParaView. 

![image](https://user-images.githubusercontent.com/43847901/101991144-14bdf680-3cab-11eb-9bed-b12dc4f7827b.png)

However when I try to make a mesh in HELYX I got the following error:

```
It looks like opal_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during opal_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  opal_shmem_base_select failed
  --> Returned value -1 instead of OPAL_SUCCESS
```

Is any idea how can I solve this issue?

Thanks in advance, Feri

**Comment by HELYX-OS** [comment]
Hi,
is OpenFoam 4.1 working from the command-line?
Can you run any serial or parallel command (e.g "snappyHexMesh" or "mpirun -np 4 snappyHexMesh parallel" )?

**Comment by safif88** [comment]
Hi,
the software works from terminal well and I can run it in serial as well as in parallel.
