### ISSUE TITLE
INSTALLATION PROBLEM +ERROR

### ISSUE THREAD

**Issue by anusha1113** [ENGYS/HELYX-OS#38]
I am currently using OpenFOAM v6 and Ubuntu18.04 
I wanted to use Helyx-OS and I am getting the following error , PLEASE HELP ME :(
java.lang.UnsatisfiedLinkError: /home/anusha/Engys/HELYX-OS/v2.4.0/ext/libvtkChartsCoreJava.so: /home/anusha/Engys/HELYX-OS/v2.4.0/ext/libjawt.so: symbol awt_Unlock version SUNWprivate_1.1 not defined in file libmawt.so with link time reference
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1939)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1864)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1854)
        at java.lang.Runtime.loadLibrary0(Runtime.java:845)
        at java.lang.System.loadLibrary(System.java:1084)
        at vtk.vtkNativeLibrary.LoadLibrary(vtkNativeLibrary.java:214)
        at eu.engys.util.VTKSettings._LoadAllNativeLibraries(VTKSettings.java:72)
        at eu.engys.util.VTKSettings.LoadAllNativeLibraries(VTKSettings.java:41)
        at eu.engys.vtk.modules.VTK3DModule.configure(VTK3DModule.java:53)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:59)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
        at com.google.inject.spi.Elements.getElements(Elements.java:101)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:133)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
        at com.google.inject.Guice.createInjector(Guice.java:95)
        at com.google.inject.Guice.createInjector(Guice.java:72)
        at eu.engys.launcher.Launcher.main(Launcher.java:96)
     0 - main                           - ERROR VTKSettings                     - vtkInteractionStyleJava NOT loaded
     4 - main                           - ERROR VTKSettings                     - vtkInteractionWidgetsJava NOT loaded
     6 - main                           - ERROR VTKSettings                     - vtkInteractionImageJava NOT loaded
    10 - main                           - ERROR VTKSettings                     - vtkGeovisCoreJava NOT loaded
    13 - main                           - ERROR VTKSettings                     - vtkAcceleratorsDaxJava NOT loaded
    14 - main                           - ERROR VTKSettings                     - vtkAcceleratorsPistonJava NOT loaded
    16 - main                           - ERROR VTKSettings                     - vtkDomainsChemistryJava NOT loaded
    18 - main                           - ERROR VTKSettings                     - vtkIOPostgreSQLJava NOT loaded
    20 - main                           - ERROR VTKSettings                     - vtkIOMPIImageJava NOT loaded
    22 - main                           - ERROR VTKSettings                     - vtkIOVPICJava NOT loaded
    24 - main                           - ERROR VTKSettings                     - vtkIOImportJava NOT loaded
    26 - main                           - ERROR VTKSettings                     - vtkIOParallelLSDynaJava NOT loaded
    27 - main                           - ERROR VTKSettings                     - vtkIOXdmf2Java NOT loaded
    29 - main                           - ERROR VTKSettings                     - vtkIOMPIParallelJava NOT loaded
    35 - main                           - ERROR VTKSettings                     - vtkIOMINCJava NOT loaded
    37 - main                           - ERROR VTKSettings                     - vtkIOParallelJava NOT loaded
    39 - main                           - ERROR VTKSettings                     - vtkIOExportJava NOT loaded
    41 - main                           - ERROR VTKSettings                     - vtkIOGDALJava NOT loaded
    43 - main                           - ERROR VTKSettings                     - vtkIOMySQLJava NOT loaded
    45 - main                           - ERROR VTKSettings                     - vtkIOFFMPEGJava NOT loaded
    50 - main                           - ERROR VTKSettings                     - vtkIOParallelExodusJava NOT loaded
    51 - main                           - ERROR VTKSettings                     - vtkIOParallelNetCDFJava NOT loaded
    53 - main                           - ERROR VTKSettings                     - vtkIOODBCJava NOT loaded
    55 - main                           - ERROR VTKSettings                     - vtkIOGeoJSONJava NOT loaded
    58 - main                           - ERROR VTKSettings                     - vtkParallelMPIJava NOT loaded
    59 - main                           - ERROR VTKSettings                     - vtkPythonInterpreterJava NOT loaded
    66 - main                           - ERROR VTKSettings                     - vtkViewsGeovisJava NOT loaded
    67 - main                           - ERROR VTKSettings                     - vtkViewsInfovisJava NOT loaded
    69 - main                           - ERROR VTKSettings                     - vtkViewsCoreJava NOT loaded
    71 - main                           - ERROR VTKSettings                     - vtkViewsContext2DJava NOT loaded
    73 - main                           - ERROR VTKSettings                     - vtkInfovisParallelJava NOT loaded
    75 - main                           - ERROR VTKSettings                     - vtkInfovisBoostGraphAlgorithmsJava NOT loaded
    81 - main                           - ERROR VTKSettings                     - vtkRenderingLODJava NOT loaded
    82 - main                           - ERROR VTKSettings                     - vtkRenderingGL2PSJava NOT loaded
    84 - main                           - ERROR VTKSettings                     - vtkRenderingFreeTypeJava NOT loaded
    85 - main                           - ERROR VTKSettings                     - vtkRenderingAnnotationJava NOT loaded
    87 - main                           - ERROR VTKSettings                     - vtkRenderingVolumeJava NOT loaded
    89 - main                           - ERROR VTKSettings                     - vtkRenderingVolumeOpenGLJava NOT loaded
    91 - main                           - ERROR VTKSettings                     - vtkRenderingFreeTypeOpenGLJava NOT loaded
    98 - main                           - ERROR VTKSettings                     - vtkRenderingMatplotlibJava NOT loaded
    99 - main                           - ERROR VTKSettings                     - vtkRenderingLICJava NOT loaded
   101 - main                           - ERROR VTKSettings                     - vtkRenderingParallelJava NOT loaded
   102 - main                           - ERROR VTKSettings                     - vtkRenderingVolumeAMRJava NOT loaded
   104 - main                           - ERROR VTKSettings                     - vtkRenderingLabelJava NOT loaded
   106 - main                           - ERROR VTKSettings                     - vtkRenderingQtJava NOT loaded
   107 - main                           - ERROR VTKSettings                     - vtkRenderingCoreJava NOT loaded
   111 - main                           - ERROR VTKSettings                     - vtkRenderingImageJava NOT loaded
   114 - main                           - ERROR VTKSettings                     - vtkRenderingContext2DJava NOT loaded
   115 - main                           - ERROR VTKSettings                     - vtkRenderingParallelLICJava NOT loaded
   117 - main                           - ERROR VTKSettings                     - vtkRenderingOpenGLJava NOT loaded
   118 - main                           - ERROR VTKSettings                     - vtkTestingRenderingJava NOT loaded
   120 - main                           - ERROR VTKSettings                     - vtkFiltersParallelMPIJava NOT loaded
   121 - main                           - ERROR VTKSettings                     - vtkFiltersReebGraphJava NOT loaded
   123 - main                           - ERROR VTKSettings                     - vtkFiltersHybridJava NOT loaded
   125 - main                           - ERROR VTKSettings                     - vtkFiltersStatisticsGnuRJava NOT loaded
   127 - main                           - ERROR VTKSettings                     - vtkFiltersParallelJava NOT loaded
   128 - main                           - ERROR VTKSettings                     - vtkFiltersParallelGeometryJava NOT loaded
   134 - main                           - ERROR VTKSettings                     - vtkFiltersParallelFlowPathsJava NOT loaded
   138 - main                           - ERROR VTKSettings                     - vtkFiltersParallelStatisticsJava NOT loaded
   141 - main                           - ERROR VTKSettings                     - vtkFiltersParallelImagingJava NOT loaded
   144 - main                           - ERROR VTKSettings                     - vtkWebGLExporterJava NOT loaded
   145 - main                           - ERROR VTKSettings                     - vtkWebCoreJava NOT loaded
   149 - main                           - ERROR VTKSettings                     - vtkChartsCoreJava NOT loaded
+++ Loading LookAndFeel +++
+++ Check License +++
+++ Loading Application +++
+++ Loading View +++
+++ Start Application +++
+++ Loading Menu Bar +++
+++ Loading Status Bar +++
+++ Loading Toolbar +++
+++ Layout Mesh +++
+++ Layout Base Mesh +++
+++ Layout Geometry +++
+++ Layout Lines +++
+++ Layout Material Point +++
+++ Layout Mesh +++
+++ Layout Custom +++
+++ Layout Case Setup +++
+++ Layout Solution Modelling +++
+++ Layout Materials +++
+++ Layout Boundary Conditions +++
+++ Layout Cell Zones +++
+++ Layout Numerical Schemes +++
+++ Layout Solver Settings +++
+++ Layout Runtime Controls +++
+++ Layout Fields Initialisation +++
+++ Layout Custom +++
+++ Layout Phases +++
+++ Layout Rigid Body Domain Motion +++
+++ Layout 6 DOF Domain Motion +++
+++ Layout Solver +++
+++ Layout Run Options +++
+++ Layout Runtime Controls +++
+++ Layout Residuals +++
+++ Layout Mesh +++
Exception in thread "GUI Dispatch Queue" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:207)
        at java.awt.Window.<init>(Window.java:535)
        at java.awt.Frame.<init>(Frame.java:420)
        at javax.swing.JFrame.<init>(JFrame.java:224)
        at eu.engys.application.AbstractApplication$2.<init>(AbstractApplication.java:128)
        at eu.engys.application.AbstractApplication.initFrame(AbstractApplication.java:128)
        at eu.engys.application.AbstractApplication$1.run(AbstractApplication.java:102)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:721)
        at java.awt.EventQueue.access$200(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:682)
        at java.awt.EventQueue$3.run(EventQueue.java:680)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:691)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

After this the cursor just stopped and I waited for a very long time to see if something will happen , but nothing happened . 
Please let me know what is the issue :(

**Comment by HELYX-OS** [comment]
Hi,
the error message says: "Exception in thread "GUI Dispatch Queue" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it."
This means that there is no display to show the application.
Please describe in detail the steps you are performing to start HELYX-OS

**Comment by anusha1113** [comment]
Hello, 
I had followed all the steps mentioned on the installation instructions   http://engys.github.io/HELYX-OS/installation/.

 When I did this command :

:~$ ~/Engys/HELYX-OS/v2.4.0/HELYX-OS.sh  

I got that error and my cursor was just blinking forever.
Hope I can install it and start working :(

**Comment by spiers818** [comment]
@anusha1113 I am having similar error when I go to launch the GUI. Did you ever resolve this issue?

**Comment by HELYX-OS** [comment]
Hi spiers818,

if you need help you need to provide more details:
- What do you mean with "similar" issue?
- What is you error message?
- What os are you using (Ubuntu 18, Ubuntu 20 CentOS7, ...)?
- Are you using a virtual machine? 
- What shell are you running from? 
- Are you running from a remote shell?

Usually errors in the form of "HELYX-OS is not working" or "HELYX-OS does not start" are related to the application being executed on a non-supported environment (e.g. using the Ubuntu shell under Windows).

Let us know what is your setup and we will try to help.

**Comment by spiers818** [comment]
Hello HELYX-OS,
I was eventually able to get the HELYX-OS GUI to run on my machine following these instructions: http://engys.github.io/HELYX-OS/installation/

What os are you using (Ubuntu 18, Ubuntu 20 CentOS7, ...)?
Ubuntu 20.04.2
Are you using a virtual machine?
yes a Gcloud Linux instance
What shell are you running from?
bash
Are you running from a remote shell?
dont think so

After, getting the HELYX-OS GUI to open I ran in to the following issue when attempting to mesh a geometry:
--> FOAM FATAL ERROR: 
[3] unknown file extension STL. Supported extensions are '.ftr', '.stl', '.stlb', '.gts', '.obj', '.ac', '.off', '.nas', '.tri' and '.vtk'
[3] 
[3]     From function bool Foam::triSurface::read(const Foam::fileName&, const Foam::word&, bool)
[3]     in file triSurface/triSurface.C at line 358.
[3] 
FOAM parallel run exiting
[3] 
[cfd06:28456] PMIX ERROR: UNREACHABLE in file ../../../src/server/pmix_server.c at line 2193
[cfd06:28456] 3 more processes have sent help message help-mpi-api.txt / mpi-abort
[cfd06:28456] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

**Comment by HELYX-OS** [comment]
Hi spiers818,
this is a different issue. What file are you trying to import?

**Comment by spiers818** [comment]
I am trying to mesh a plate in .stl (ASCII) format contained in a user defined Bounding box.
[snappyHexMesh.log](https://github.com/ENGYS/HELYX-OS/files/6191581/snappyHexMesh.log)

**Comment by HELYX-OS** [comment]
Can you also attach the stl file?

**Comment by spiers818** [comment]
[ductPlate_small_cfd.zip](https://github.com/ENGYS/HELYX-OS/files/6191605/ductPlate_small_cfd.zip)

**Comment by HELYX-OS** [comment]
Can you simply make the extension lowercase (i.e. ductPlate_small_cfd.stl) and see if it works?

**Comment by spiers818** [comment]
:) It worked. Thanks
