### ISSUE TITLE
gpg keys not installed

### ISSUE THREAD

**Issue by geraldebberink** [ENGYS/HELYX-OS#39]
When installing HELYX and the Kernel on Ubuntu 20.04 the correct GPG keys are not loaded so the installation of openfoam fails.

I cannot find the install script in the repo so I cannot make a pull request.

**Comment by HELYX-OS** [comment]
Hi geraldebberink, HELYX-OS 2.4.0 is designed to work natively with OpenFOAM version 4.1. The resources of such version have been changed/removed so the automatic kernel installation does not work anymore. If you want to use OpenFOAM 4.1 you have to install it manually.
Using OpenFOAM > 4.1 is not guaranteed to work. Some dictionaries are written with a syntax that may not be supported anymore. For small changes you can still use the custom interface available in HELYX-OS which allows you to override the way things are written to disk (e.g. [#27](https://github.com/ENGYS/HELYX-OS/issues/27)).
