### ISSUE TITLE
OpenFOAM 8 is intalled on ubuntu 20.04

### ISSUE THREAD

**Issue by geraldebberink** [ENGYS/HELYX-OS#40]
After solving #39 openFOAM 8 is installed. 
So HELYX cannot start the solvers due to #27 popping up.

**Comment by HELYX-OS** [comment]
Hi geraldebberink,
as stated here https://github.com/ENGYS/HELYX-OS/issues/39
"Using OpenFOAM > 4.1 is not guaranteed to work. Some dictionaries are written with a syntax that may not be supported anymore. For small changes you can still use the custom interface available in HELYX-OS which allows you to override the way things are written to disk (e.g. #27)."

**Comment by spiers818** [comment]
@HELYX-OS are there plans for updating HELYX-OS to work with newer versions of OpenFOAM?
