### ISSUE TITLE
Boundary Condition Reset

### ISSUE THREAD

**Issue by spiers818** [ENGYS/HELYX-OS#43]
Hello, 
should the boundary conditions in HELYX-OS -> Case Setup reset to default after every remeshing?
If no, any ideas why this maybe happening? 
If yes, any way to store boundary conditions?
thanks

**Comment by HELYX-OS** [comment]
Hi spiers818,
this functionality is only available in our enterprise solution [HELYX](https://engys.com/products/helyx) but not on HELYX-OS.
