### ISSUE TITLE
Paraview not starting when using Docker

### ISSUE THREAD

**Issue by Octavarius** [ENGYS/HELYX-OS#5]
Hi, 

first of all, many thanks for offering a new version of Helyx os. This is a tremendous package for OpenFoam noobs like me.

I have the following issue here, running on Ubuntu 16.06. 
When docker is ticked in the pref menu, everything seems to work fine, except for Paraview. I'm getting the following:
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
/opt/OpenFOAM
Created temporary 'newCase.OpenFOAM'
/opt/OpenFOAM/ThirdParty-v1606+/platforms/linux64Gcc/ParaView-5.0.1/lib/paraview-5.0/paraview: error while loading shared libraries: libQtHelp.so.4: cannot open shared object file: No such file or directory

On the other hand, if I untick docker, paraview being installed on the system, paraview works fine, but the rest does not work anymore obviously. Any idea on what's happening here ?

Thanks!

**Comment by HELYX-OS** [comment]
Hi,

we were able to reproduce your issue, and we can confirm it is a bug.
We are planning to fix it in the next HELYX-OS release.

Thanks for reporting that.
In the meantime you should tick and untick the docker check to make it work.
