### ISSUE TITLE
Backwards compatibility

### ISSUE THREAD

**Issue by outbound-pt** [ENGYS/HELYX-OS#6]
Greetings,

Are there available versions for OF2.2.2 or 2.3.1, or is it viable to use the OF4.1 version to generate a mesh and then copy paste the polyMesh folder into an older OF2.2.2 case folder?

Best regards,

**Comment by dcombest** [comment]
Hello outbound-pt,

We still have [an old release](https://github.com/ENGYS/HELYX-OS/releases) out on the HELYX-OS project that will work with OpenFOAM version 2.4.0.  The current version (HELYX-OS v2.4.0) will only work with OpenFOAM 4.1 meshing and solving.  However, in most cases you can try to move the polyMesh folders to use in old solvers (depends on how old of OpenFOAM you want to work with).  Good luck.

**Comment by outbound-pt** [comment]
This is very helpful.

Thank you!
