### ISSUE TITLE
setFields gets overwritten

### ISSUE THREAD

**Issue by attesz86** [ENGYS/HELYX-OS#8]
Hello,

when adding a volVectorFieldValue U (0 0 0) to a custom setFieldsDict, the string will be replaced with fieldValues (0 0 0) which is wrong syntax. With volScalarFieldValue there is no problem.

**Comment by HELYX-OS** [comment]
Hi,

in the next HELYX-OS release it will be possible to initialise U with the CellSet type, therefore you will not need to use custom anymore.
For the time being I suggest you create a Custom->RawFile with name "setFieldsDict", instead of using the Custom->Dictionary type.

Cheers
